name: Security audit
on:
  # When any of these files change.
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

  # On PRs.
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  # Once a week at midnight.
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}